version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: mix
    directory: /
    target-branch: master
    allow:
      - dependency-type: all
    versioning-strategy: auto
    schedule:
      interval: daily
      time: "06:00"
      timezone: America/Toronto
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: /
    rebase-strategy: auto
    commit-message:
      prefix: Dependabot
    labels:
      - Security
