name: Run Test Suite

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.1.2"
          elixir-version: "1.14.1"
      - run: MIX_ENV=test mix deps.get
      - run: MIX_ENV=test mix compile
      - run: mix test
